config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  resources :wikis
  resources :collaborators, only: [:create, :destroy]
  resources :charges, only: [:new, :create]

  devise_for :users

  get 'downgrade', to: 'charges#downgrade'

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  def self.default
    10_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis
  has_many :collaborators

  enum role: [:standard, :premium, :admin]

  after_initialize :init

  def init
    self.role ||= :standard
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators

  default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  include Pundit
  protect_from_forgery

  def after_sign_in_path_for(resource)
    wikis_path
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    current_user.premium!
    redirect_to edit_user_registration_path


  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  def downgrade
    current_user.wikis.where(private: true).update_all(private: false)
    current_user.standard!
    redirect_to edit_user_registration_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    @user = User.where(email: params[:email]).take
    @wiki = Wiki.find(params[:wiki_id])

    if @user == nil
      flash[:notice] = "User could not be found."
      redirect_to edit_wiki_path(@wiki)

    elsif @wiki.users.include?(@user)
      flash[:notice] = "User is already a collaborator."
      redirect_to edit_wiki_path(@wiki)

    else
      @collaborator = Collaborator.new
      @collaborator.user_id = @user.id
      @collaborator.wiki_id = @wiki.id

      if @collaborator.save
        flash[:notice] = "Collaborator added."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:notice] = "Error. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki

    if @collaborator.destroy
      flash[:notice] = "Collaborator removed."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:alert] = "Error. Please try again."
      redirect_to edit_wiki_path(@wiki)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user_id = current_user.id

    if @wiki.save
      flash[:notice] = "Wiki post was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(body)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    markdown.render(body).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper

  def is_authorized
    current_user.role == "premium"
  end

end

app/views/charges/new.html.erb
.center-text
  %h1 Benefits for Premium Users!
  %div
    %h3 For just $10.00...
    %h3 You can create private Wikis.
  %div
    = form_tag charges_path do
      %h4 Let's get started!
      %script.stripe-button{"data-amount" => @stripe_btn_data[:amount], "data-description" => @stripe_btn_data[:description], "data-key" => @stripe_btn_data[:key], :src => "https://checkout.stripe.com/checkout.js"}

app/views/collaborators/_form.html.erb
<div class= 'form-group'>
  <h3>Collaborators</h3>
    <% if @wiki.user == current_user %>
      <%= form_tag(collaborators_path, action: :create, method: :post) do%>
        <%= hidden_field_tag :wiki_id, @wiki.id %>
        Enter email of the collaborator: <%= text_field_tag :email %>
        <%= submit_tag 'Add collaborator' %>
      <% end %>
    <% end %>

    <% @wiki.collaborators.each do |user| %>
      <div>
        <%= user.user.email %>
        <% if @wiki.user == current_user %>
          <%= link_to "Remove collaborator", user, method: :delete, data: {confirm: 'Are you sure you want remove user as a collaborator?'} %>
        <% end %>
    </div>
    <% end %>
</div>

app/views/collaborators/_form.html.haml
.form-group
  %h3 Collaborators
  - if @wiki.user == current_user
    = form_tag(collaborators_path, action: :create, method: :post) do
      = hidden_field_tag :wiki_id, @wiki.id
      Enter email of the collaborator: #{text_field_tag :email}#{submit_tag 'Add collaborator'}
  - @wiki.collaborators.each do |user|
    %div
      = user.user.email
      - if @wiki.user == current_user
        = link_to "Remove collaborator", user, method: :delete, data: {confirm: 'Are you sure you want remove user as a collaborator?'}

app/views/layouts/application.html.haml
%html
  %head
    %title Blocipedia
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Home", welcome_index_path
        %li= link_to "Wiki", wikis_path
        %li= link_to "About", welcome_about_path
        .pull-right.user-info
          - if user_signed_in?
            Signed in as:
            %strong= current_user.email
            |
            \#{link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'} -
            \#{link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to 'Sign Up', new_user_session_path, :class => 'navbar-link'
      - if flash[:notice]
        .alert.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = flash[:notice]
      - elsif flash[:alert]
        .alert.alert-warning
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          - flash[:alert]
      = yield

app/views/welcome/about.html.haml
%h1 Welcome#about
%p Find me in app/views/welcome/about.html.erb

app/views/welcome/index.html.haml
%h1 Welcome
%div
  %p Please feel free to create a wiki post!

app/views/wikis/edit.html.haml
%h1 Edit Wiki
.row
  .col-md-4
    %p Basic Markdown Guidelines
    %ul
      %li
        %b Headers
        = markdown("```# Heading 1```")
        = markdown("```## Heading 2```")
      %li
        %b Emphasis
        = markdown("```*italic* and **bold**```")
      %li
        %b Blockquotes
        = markdown("```> quote```")
      %li
        %b Links
        = markdown("```[linked text](url)```")
      %li
        %b Images
        = markdown("```![Image Name](url)```")
  .col-md-8
    = form_for @wiki do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class:'form-control', placeholder: "Enter the title"
      .form-group
        = f.label :body
        = f.text_area :body , class:'form-control', placeholder: "Enter the body - Markdown supported"
      - if current_user.admin? || current_user.premium?
        .form-group
          = f.label :private, class: 'checkbox' do
            = f.check_box :private, checked: @wiki.private?
            Private wiki
      .form-group
        = f.submit "Save", class:'btn btn-success'
    .form-group
      = render partial: 'collaborators/form'

app/views/wikis/index.html.haml
%h1 All Wikis
%div
  - @wikis.each do |wiki|
    .media
      .media-body
        %h4.media-heading
        %p= link_to wiki.title, wiki
  .col-md-4
    = link_to "New Wiki", new_wiki_path, class: 'btn btn-success'

app/views/wikis/new.html.haml
%h1 New Wiki
.row
  .col-md-4
    %p Basic Markdown Guidelines
    %ul
      %li
        %b Headers
        = markdown("```# Heading 1```")
        = markdown("```## Heading 2```")
      %li
        %b Emphasis
        = markdown("```*italic* and **bold**```")
      %li
        %b Blockquotes
        = markdown("```> quote```")
      %li
        %b Links
        = markdown("```[linked text](url)```")
      %li
        %b Images
        = markdown("```![Image Name](url)```")
  .col-md-8
    = form_for @wiki do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class:'form-control', placeholder: "Enter the title"
      .form-group
        = f.label :body
        = f.text_area :body , class:'form-control', placeholder: "Enter the body"
      - if current_user.admin? || current_user.premium?
        .form-group
          = f.label :private, class: 'checkbox' do
            = f.check_box :private
            Private wiki
      .form-group
        = f.submit "Save", class:'btn btn-success'
  .form-group
    = render partial: 'collaborators/form'

app/views/wikis/show.html.haml
%h1= @wiki.title
.row
  .col-md-8
    %p= markdown(@wiki.body)
  .col-md-4
    = link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success'
    = link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'}